name: hyprpain

description: wip

base-image: quay.io/fedora-ostree-desktops/base
image-version: 40 

modules:
  - from-file: core-scripts.yml
  - from-file: core-packages.yml
  - from-file: remove-packages.yml
  - type: signing 



