name: hyprpain

description: wip

base-image: quay.io/fedora-ostree-desktops/base
image-version: 40 

modules:
  - from-file: scripts.yml
  - from-file: packages.yml
  - from-file: fonts.yml
  - from-file: default-flatpaks.yml
  - from-file: files.yml
  - type: justfiles
  - from-file: remove-packages.yml
  - from-file: services.yml
  - type: signing  



