type: systemd
system:
  enabled:
    - hyprpain-setup.service
    - greetd-user.service
    - greetd-workaround.service
    - libvirt-workaround.service
    - swtpm-workaround.service
    - greetd.service
    - lactd.service
    - libvirtd.service
 


