type: systemd
system:
  enabled:
    - greetd-user.service
    - greetd-workaround.service
    - libvirt-workaround.service
    - swtpm-workaround.service
    - greetd.service
    - set-kargs.service
    - lactd.service
 


